### ISSUE TITLE
no dist

### ISSUE THREAD

**Issue by dagostinelli** [jsweb/font-awesome-base64#1]
The Readme says there's a dist folder, but it's not there in the repo.

**Comment by alexbruno** [comment]
The `dist` folder is listed in `.gitignore` because it is not required to maintain it versioned in repo.
There is a CI hook to build the package and publish to NPM.
Files in `dist` can be found when you install the package from NPM or if you target **unpkg** CDN:

https://unpkg.com/@jsweb/font-awesome-base64/dist/fa-all.css
